name: Release
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish to Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Create zip
        run: ./gradlew mavenZip
        env:
          VERSION: ${{ github.event.release.tag_name }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - name: Upload zip
        run: |
          cd ${{github.workspace}}/build/deliverables
          gh release upload ${{ github.event.release.tag_name }} dom4future-${{ github.event.release.tag_name }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
